### PR TITLE
Kilian/online offline adaptation

### PR DESCRIPTION
**Pull request by KilianFt**

### CODE REVIEW

**Comment by KilianFt** [comment]
@CodiumAI-Agent /review

**Comment by manuel-delverme** [comment]
The AI made some good points

**Comment by KilianFt** [comment]
@CodiumAI-Agent /review

**Comment by KilianFt** [comment]
@CodiumAI-Agent /improve [--extended]

**Comment by KilianFt** [comment]
@CodiumAI-Agent /improve --extended

**Pull request merged**
